[18/Jan/2025 12:51:49] ERROR [basehttp.py:212] [log_message] "POST /generate-video/ HTTP/1.1" 500 79
[18/Jan/2025 13:03:46] ERROR [basehttp.py:212] [log_message] "POST /generate-video/ HTTP/1.1" 500 79
[18/Jan/2025 13:04:28] ERROR [basehttp.py:212] [log_message] "POST /generate-video/ HTTP/1.1" 500 79
[18/Jan/2025 20:55:14] ERROR [basehttp.py:212] [log_message] "POST /send-emails/ HTTP/1.1" 500 39
[18/Jan/2025 20:55:57] ERROR [basehttp.py:212] [log_message] "POST /send-emails/ HTTP/1.1" 500 39
[18/Jan/2025 20:56:12] ERROR [basehttp.py:212] [log_message] "POST /send-emails/ HTTP/1.1" 500 39
[18/Jan/2025 20:56:43] ERROR [basehttp.py:212] [log_message] "POST /send-emails/ HTTP/1.1" 500 39
[18/Jan/2025 20:57:20] ERROR [basehttp.py:212] [log_message] "POST /send-emails/ HTTP/1.1" 500 10697
[19/Jan/2025 01:26:35] ERROR [consumer.py:493] [_error_handler] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 2.00 seconds... (1/100)

[19/Jan/2025 01:26:37] ERROR [consumer.py:493] [_error_handler] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 4.00 seconds... (2/100)

[19/Jan/2025 01:26:41] ERROR [consumer.py:493] [_error_handler] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 6.00 seconds... (3/100)

[19/Jan/2025 01:26:47] ERROR [consumer.py:493] [_error_handler] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 8.00 seconds... (4/100)

[19/Jan/2025 01:26:55] ERROR [consumer.py:493] [_error_handler] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 10.00 seconds... (5/100)

[19/Jan/2025 01:27:05] ERROR [consumer.py:493] [_error_handler] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 12.00 seconds... (6/100)

[19/Jan/2025 01:27:17] ERROR [consumer.py:493] [_error_handler] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 14.00 seconds... (7/100)

[19/Jan/2025 01:27:31] ERROR [consumer.py:493] [_error_handler] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 16.00 seconds... (8/100)

[19/Jan/2025 01:27:47] ERROR [consumer.py:493] [_error_handler] consumer: Cannot connect to redis://localhost:6379/0: Error 111 connecting to localhost:6379. Connection refused..
Trying again in 18.00 seconds... (9/100)

[19/Jan/2025 01:30:45] ERROR [basehttp.py:213] [log_message] "POST /generate-video/ HTTP/1.1" 500 79
[19/Jan/2025 01:34:21] ERROR [basehttp.py:213] [log_message] "POST /generate-video/ HTTP/1.1" 500 79
[19/Jan/2025 01:36:35] ERROR [basehttp.py:213] [log_message] "POST /generate-video/ HTTP/1.1" 500 79
[19/Jan/2025 01:37:16] ERROR [basehttp.py:213] [log_message] "POST /generate-video/ HTTP/1.1" 500 79
[19/Jan/2025 02:12:26] ERROR [basehttp.py:213] [log_message] "POST /send-emails/ HTTP/1.1" 500 53
